using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using SkyGroundLabs.Data.Sql.Mapping;

namespace Ion.Common.Data
{
	[Table("UserClockingSpecialCodes")]
	public class UserClockingSpecialCode 
	{
		public long ID { get; set; }

		public string Code { get; set; }

		public string Description { get; set; }

		public bool IsAutoGenerated { get; set; }
	}
}
